version: 0.2
env:
  shell: bash
  variables:
    FLYWAY_VERSION: "7.11.2"
    # Needed on 1st run
    # https://flywaydb.org/documentation/configuration/parameters/baselineOnMigrate
    FLYWAY_BASELINE_ON_MIGRATE: true
    FLYWAY_SCHEMAS: demoapp
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/${FLYWAY_VERSION}/flyway-commandline-${FLYWAY_VERSION}.tar.gz -o flyway-commandline-${FLYWAY_VERSION}.tar.gz
      - mkdir -p /opt/flyway
      - tar -xzf flyway-commandline-${FLYWAY_VERSION}.tar.gz --strip-components=1 -C /opt/flyway
      - chmod +x /opt/flyway/flyway
      - ln -s /opt/flyway/flyway /usr/local/bin/flyway
      # Add the RDS Root certs
      - curl -L https://truststore.pki.rds.amazonaws.com/us-east-1/us-east-1-bundle.pem -o us-east-1-bundle.pem
      - keytool -importcert -alias AWS-RDS -file us-east-1-bundle.pem -keystore /opt/flyway/jdbc_truststore.p12 -storetype pkcs12 -noprompt -storepass changeit
      - keytool -list -keystore /opt/flyway/jdbc_truststore.p12 -noprompt -storepass changeit
  pre_build:
    commands:
      - export FLYWAY_USER=$(echo "${ADMIN_CREDS}" | jq -r .username)
      - export FLYWAY_PASSWORD=$(echo "${ADMIN_CREDS}" | jq -r .password)
      - export FLYWAY_URL="${FLYWAY_URL}?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2&trustCertificateKeyStoreType=PKCS12"
      - export FLYWAY_URL="${FLYWAY_URL}&trustCertificateKeyStorePassword=changeit&trustCertificateKeyStoreUrl=file:/opt/flyway/jdbc_truststore.p12&serverTimezone=UTC"
      - export FLYWAY_PLACEHOLDERS_APPUSER=$(echo "${APP_USER_CREDS}" | jq -r .username)
      - export FLYWAY_PLACEHOLDERS_APPUSERPW=$(echo "${APP_USER_CREDS}" | jq -r .password)
  build:
    on-failure: ABORT
    commands:
      - flyway validate -ignorePendingMigrations=true
      - flyway migrate
      - flyway info
