# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: "3.9"

services:
  springboot-app:
    build:
      context: springboot-app
      dockerfile: Dockerfile
    mem_reservation: 512M
    secrets:
      - appuser_password
      - jdbc_truststore_password
      - jdbc_truststore_path
      - source: root_ca
        target: ca.crt
        mode: 0600
      - source: server_cert
        target: server.crt
        mode: 0600
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - demo
    links:
      - postgres
    restart: always
    depends_on:
      - postgres
    environment:
      JDBC_TRUSTSTORE_PATH: /run/secrets/jdbc_truststore_path
      AWS_REGION: us-east-1
      SPRING_PROFILES_ACTIVE: docker
      JAVA_TOOL_OPTIONS: "-XX:InitialRAMPercentage=70 -XX:MaxRAMPercentage=70 -Dfile.encoding=UTF-8"

  postgres:
    image: postgres:15
    user: postgres
    command:
      - "-c"
      - "ssl=on"
      - "-c"
      - "ssl_cert_file=/run/secrets/server.crt"
      - "-c"
      - "ssl_key_file=/run/secrets/server.key"
      - "-c"
      - "ssl_ca_file=/run/secrets/ca.crt"
    networks:
      - demo

    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/root_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./data-migration/sql/V2__initial_tables.sql:/docker-entrypoint-initdb.d/V2__initial_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    secrets:
      - source: root_password
      - source: appuser_password
      - source: root_ca
        target: ca.crt
        mode: 0600
      - source: server_key
        target: server.key
        mode: 0600
      - source: server_cert
        target: server.crt
        mode: 0600

secrets:
  root_password:
    file: ./credentials/root_password
  appuser_password:
    file: ./credentials/appuser_password
  jdbc_truststore_password:
    file: ./credentials/jdbc_truststore_password
  jdbc_truststore_path:
    file: ./credentials/jdbc_truststore_local.p12
  root_ca:
    file: ./credentials/ca.crt
  server_key_der:
    file: ./credentials/server.key.der
  server_key:
    file: ./credentials/server.key
  server_cert:
    file: ./credentials/server.crt
networks:
  demo:
