CREATE DATABASE IF NOT EXISTS demoapp;

USE demoapp;

CREATE USER '${appuser}'@'%' IDENTIFIED BY '${appuserpw}' REQUIRE SSL;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE,CREATE TEMPORARY TABLES, EXECUTE ON demoapp.* TO '${appuser}'@'%';
