server:
  undertow:
    accesslog:
      enabled: true
      dir: "/var/log/demoapp"
      file-date-format:
      prefix: "access_log"
      suffix:
spring:
  application:
    name: demoapp
  config:
    import: "configtree:/run/secrets/"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: "jdbc:postgresql://postgres:5432/postgres"
    username: "appuser"
    password: "${appuser_password}"
    hikari:
      maximum-pool-size: 20
      data-source-properties:
        ssl: true
        sslmode: verify-ca
        sslcert: /run/secrets/server.crt
        sslrootcert: /run/secrets/ca.crt

management:
  server:
    port: 8081
  endpoint:
    health:
      probes:
        enabled: true
    info:
      enabled:
    logfile:
      enabled: true
      external-file: /var/log/demoapp/access_log_management
