server:
  undertow:
    accesslog:
      enabled: true
      dir: "/var/log/demoapp"
      file-date-format:
      prefix: "access_log"
      suffix:
  # ensures that you'll get the x-forwarded headers form the ALB
  forward-headers-strategy: native

spring:
  application:
    name: demoapp
  config:
    # https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-SNAPSHOT/reference/html/index.html#adding-prefix-to-property-keys
    import:
      - aws-secretsmanager:/secret/${spring.application.name}/appuser?prefix=appuser.
  cloud:
    aws:
      secretsmanager:
        reload:
          strategy: restart_context
  datasource:
    url: "jdbc:postgresql://${appuser.host}:${appuser.port}/${appuser.dbname}"
    username: "${appuser.username}"
    password: "${appuser.password}"
    hikari:
      maximum-pool-size: 20
      data-source-properties:
        currentSchema: demoapp
        ssl: true
        sslmode: verify-ca
        # Since we are loading the RDS certs into the keystore, we must provide this
        # sslfactory impl in order for it work. Otherwise, PG will look at the file system
        # for specific certs located in specific locations.
        sslfactory: "org.postgresql.ssl.DefaultJavaSSLFactory"

management:
  server:
    port: 8081
    ssl:
      enabled: false
  endpoints:
    web:
      exposure:
        include: restart,health,info
  endpoint:
    restart:
      enabled: true
    health:
      probes:
        enabled: true
      enabled: true

    info:
      enabled: true
    logfile:
      enabled: true
      external-file: /var/log/demoapp/access_log_management
