server:
  undertow:
    accesslog:
      enabled: true
      dir: "/var/log/demoapp"
      file-date-format:
      prefix: "access_log"
      suffix:
  # ensures that you'll get the x-forwarded headers form the ALB
  forward-headers-strategy: native

spring:
  application:
    name: demoapp
  datasource:
    url: "jdbc:postgresql://${demoapp.db.host}:${demoapp.db.port}/${demoapp.db.name}"
    username: "${demoapp.db.username}"
    password: "${demoapp.db.password}"
    hikari:
      maximum-pool-size: 20
      data-source-properties:
        currentSchema: demoapp
        ssl: true
        sslmode: verify-ca
        sslrootcert: /opt/app/global-bundle.pem

management:
  server:
    port: 8081
    ssl:
      enabled: false
  endpoints:
    web:
      exposure:
        include: restart,health,info
  endpoint:
    restart:
      enabled: true
    health:
      probes:
        enabled: true
      enabled: true

    info:
      enabled: true
    logfile:
      enabled: true
      external-file: /var/log/demoapp/access_log_management
