spring:
  applictaion:
    name: demoapp
management:
  server:
    port: 8081
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    io:
      awspring:
        cloud:
          paramstore:
            AwsParamStorePropertySource=debug: