server:
  undertow:
    accesslog:
      enabled: true
      dir: "/tmp"
      file-date-format:
      prefix: stdout
      suffix:
spring:
  application:
    name: demoapp
  config:
    import: "configtree:./credentials/"
  datasource:
    url: "jdbc:postgresql://localhost/demoapp"
    username: "appuser"
    password: "${appuser_password}"
    hikari:
      maximum-pool-size: 5
      data-source-properties:
        ssl: true
