
aws:
  paramstore:
    enabled: true
  secretsmanager:
    enabled: true
spring:
  config:
    import:
      - "aws-secretsmanager:/secret/demoapp/appuser"
      - "aws-parameterstore:/config/demoapp/spring/data/jdbc/url"
    activate:
      on-profile: aws
  datasource:
    url: "${spring.data.jdbc.url}"
    username: "appuser"
    password: "${appuser}"
    hikari:
      maximum-pool-size: 20
      data-source-properties:
        serverTimezone: UTC
        sslMode: VERIFY_CA
        fallbackToSystemTrustStore: true
        useLegacyDatetimeCode: false
        # Recommended MySQL connection settings from HikariCP
        # https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

