server:
  http2:
    enabled: true
  undertow:
    accesslog:
      enabled: true
      dir: "/var/log/demoapp"
      file-date-format:
      prefix: "access_log"
      suffix:
spring:
  application:
    name: demoapp
  config:
    import: "configtree:/run/secrets/"
  datasource:
    url: "jdbc:mysql://mysql:3306/demoapp"
    username: "appuser"
    password: "${appuser_password}"
    hikari:
      maximum-pool-size: 20
      data-source-properties:
        serverTimezone: UTC
        sslMode: VERIFY_CA
        trustCertificateKeyStorePassword: "${jdbc_truststore_password}"
        trustCertificateKeyStoreType: "PKCS12"
        trustCertificateKeyStoreUrl: "file:${jdbc.truststore.path}"
        fallbackToSystemTrustStore: false
        useLegacyDatetimeCode: false
        # Recommended MySQL connection settings from HikariCP
        # https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
management:
  server:
    port: 8081
  endpoint:
    health:
      probes:
        enabled: true
    info:
      enabled:
    logfile:
      enabled: true
      external-file: /var/log/demoapp/access_log_management
