aws:
  paramstore:
    enabled: true
  secretsmanager:
    enabled: true
spring:
  application:
    name: demoapp
  config:
    import:
      - "aws-secretsmanager:/secret/${spring.application.name}/appuser"
    activate:
      on-profile: aws
  datasource:
    url: "jdbc:mysql://${host}:${port}/demoapp"
    username: "appuser"
    password: "${password}"
    hikari:
      maximum-pool-size: 20
      data-source-properties:
        serverTimezone: UTC
        sslMode: VERIFY_CA
        fallbackToSystemTrustStore: true
        useLegacyDatetimeCode: false
        # Recommended MySQL connection settings from HikariCP
        # https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
