spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/demoapp"
    username: "appuser"
    password: "${APPUSER_PASSWORD}"
    hikari:
      maximum-pool-size: 5
      data-source-properties:
        serverTimezone: UTC
        sslMode: VERIFY_CA
        trustCertificateKeyStorePassword: "${TRUSTSTORE_PASSWORD}"
        trustCertificateKeyStoreType: PKCS12
        trustCertificateKeyStoreUrl: "file:${PWD}/credentials/truststore.p12"
        fallbackToSystemTrustStore: false
        useLegacyDatetimeCode: false
        # Recommended MySQL connection settings from HikariCP
        # https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false