spring:
  datasource:
    url: "jdbc:mysql://mysql:3306/demoapp"
    username: "appuser"
    password: "${docker.secrets.appuser_password}"
    hikari:
      maximum-pool-size: 20
      data-source-properties:
        serverTimezone: UTC
        sslMode: VERIFY_CA
        trustCertificateKeyStorePassword: "${docker.secrets.truststore_password}"
        trustCertificateKeyStoreType: "PKCS12"
        trustCertificateKeyStoreUrl: "file:/opt/app/truststore.p12"
        fallbackToSystemTrustStore: false
        useLegacyDatetimeCode: false
        # Recommended MySQL connection settings from HikariCP
        # https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false