aws:
  paramstore:
    enabled: true
  secretsmanager:
    enabled: true
    default-context: "shared"
    name: "${spring.application.name}"
server:
  undertow:
    accesslog:
      enabled: true
      dir: "/var/log/demoapp"
      file-date-format:
      prefix: "access_log"
      suffix:
  # ensures that you'll get the x-forwarded headers form the ALB
  forward-headers-strategy: native
spring:
  application:
    name: demoapp
  config:
    import:
      - "aws-secretsmanager:/secret/${spring.application.name}/appuser?postgres"
  datasource:
    url: "jdbc:postgresql://${postgres.host}:${postgres.port}/demoapp"
    username: "${postgres.username}"
    password: "${postgres.password}"
    hikari:
      maximum-pool-size: 20
      data-source-properties:
        currentSchema: demoapp
        ssl: true
        sslmode: verify-ca

management:
  server:
    port: 8081
  endpoint:
    health:
      probes:
        enabled: true
    info:
      enabled:
    logfile:
      enabled: true
      external-file: /var/log/demoapp/access_log_management
